import Profile from "./pages/dashboard/profile";

// routes.js
const routes = {
  home: '/',
  about: '/about',
  contact: '/contact',
  partnership: '/partnership/1',
  partnership2: '/partnership/2',
  partnership3: '/partnership/3',
  partnership4: '/partnership/4',
  partnership5: '/partnership/success',
  account: '/account',
  login: '/account/login',
  forgotPassword1: '/account/forgot-password/step1',
  forgotPassword2: '/account/forgot-password/step2',
  dashboard: '/dashboard',
  profile: '/dashboard/profile',
  settings: '/dashboard/settings',
  shop: '/dashboard/shop',
  shopAdd: '/dashboard/shop/add',
  shopEdit: '/dashboard/shop/edit/[shopNo]',
  shopView: '/dashboard/shop/view/[shopNo]',
  shopRequest: '/dashboard/shop/requests',
  shopRequestManage: '/dashboard/shop/requests/manage/[requestNo]',
  inquiry: '/dashboard/inquiry',
  inquiryView: '/dashboard/inquiry/view/[inquiryNo]',
  product: '/dashboard/product',
  productAdd: '/dashboard/product/add',
  productEdit: '/dashboard/product/edit/[productNo]',
  productView: '/dashboard/product/view/[productNo]',
  order: '/dashboard/order',
  orderAdd: '/dashboard/order/add/[orderNo]',
  orderEdit: '/dashboard/order/edit/[orderNo]',
  orderView: '/dashboard/order/view/[orderNo]',
  orderReserve: '/dashboard/order/reserve',
  orderReserveAdd: '/dashboard/order/reserve/add/[orderNo]',
  orderReserveEdit: '/dashboard/order/reserve/edit/[orderNo]',
  orderReserveView: '/dashboard/order/reserve/view/[orderNo]',
  user: '/dashboard/user',
  userAdd: '/dashboard/user/add',
  userEdit: '/dashboard/user/edit/[userNo]',
  userView: '/dashboard/user/view/[userNo]',
  maintenance: '/dashboard/maintenance',
  types: '/dashboard/maintenance/types',
  typesAdd: '/dashboard/maintenance/types/add/[typeNo]',
  categories: '/dashboard/maintenance/categories',
  categoriesAdd: '/dashboard/maintenance/categories/add/[categoryNo]',
  tags: '/dashboard/maintenance/tags',
  tagsAdd: '/dashboard/maintenance/tags/add/[tagNo]',
  colors: '/dashboard/maintenance/colors',
  colorsAdd: '/dashboard/maintenance/colors/add/[colorNo]',
  measurements: '/dashboard/maintenance/measurements',
  measurementsAdd: '/dashboard/maintenance/measurements/add/[measurementNo]',
  units: '/dashboard/maintenance/units',
  unitsAdd: '/dashboard/maintenance/units/add/[unitNo]',
  sizes: '/dashboard/maintenance/sizes',
  sizesAdd: '/dashboard/maintenance/sizes/add/[unitNo]',
  virtualFitting: '/dashboard/virtual-fitting',
  addVirtualFitting: '/dashboard/virtual-fitting/add',
};

export default routes;