// routes.js
const routes = {
  home: '/',
  about: '/about',
  contact: '/contact',
  partnership: '/partnership',
  account: '/account',
  login: '/account/login',
  forgotPassword1: '/account/forgot-password/step1',
  forgotPassword2: '/account/forgot-password/step2',
  dashboard: '/dashboard',
  settings: '/dashboard/settings',
  shop: '/dashboard/shop',
  shopAdd: '/dashboard/shop/add/[shopNo]',
  shopEdit: '/dashboard/shop/edit/[shopNo]',
  shopView: '/dashboard/shop/view/[shopNo]',
  shopRequest: '/dashboard/shop/requests',
  shopRequestEdit: '/dashboard/shop/requests/edit/[requestNo]',
  inquiry: '/dashboard/inquiry',
  inquiryAdd: '/dashboard/inquiry/add/[inquiryNo]',
  inquiryEdit: '/dashboard/inquiry/edit/[inquiryNo]',
  inquiryView: '/dashboard/inquiry/view/[inquiryNo]',
  product: '/dashboard/product',
  productAdd: '/dashboard/product/add/[productNo]',
  productEdit: '/dashboard/product/edit/[productNo]',
  productView: '/dashboard/product/view/[productNo]',
  order: '/dashboard/order',
  orderAdd: '/dashboard/order/add/[orderNo]',
  orderEdit: '/dashboard/order/edit/[orderNo]',
  orderView: '/dashboard/order/view/[orderNo]',
  orderReserve: '/dashboard/order/reserve',
  orderReserveAdd: '/dashboard/order/reserve/add/[orderNo]',
  orderReserveEdit: '/dashboard/order/reserve/edit/[orderNo]',
  orderReserveView: '/dashboard/order/reserve/view/[orderNo]',
  user: '/dashboard/user',
  userAdd: '/dashboard/user/add/[userNo]',
  userEdit: '/dashboard/user/edit/[userNo]',
  userView: '/dashboard/user/view/[userNo]',
};

export default routes;