/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        rainbow1: "var(--rainbow1)",
        rainbow2: "var(--rainbow2)",
        rainbow3: "var(--rainbow3)",
        rainbow4: "var(--rainbow4)",
        rainbow5: "var(--rainbow5)",
        rainbow6: "var(--rainbow6)",
        lightBackground: "var(--light-background)",
        darkBackground: "var(--dark-background)",
        foreground: "var(--foreground)",
        transparent: "var(--transparent)",
        white: "var(--white)",
        oneOpacityWhite: "var(--one-opacity-white)",
        tenOpacityWhite: "var(--ten-opacity-white)",
        twentyfiveOpacityWhite: "var(--twentyfive-opacity-white)",
        lowWhite: "var(--low-white)",
        lowGreyWhite: "var(--low-grey-white)",
        greyWhite: "var(--grey-white)",
        lowGrey: "var(--low-grey)",
        grey: "var(--grey)",
        darkGrey: "var(--dark-grey)",
        dark: "var(--dark)",
        fiftyOpacityDark: "var(--fifty-opacity-dark)",
        seventyfiveOpacityDark: "var(--seventyfive-opacity-dark)",
        black: "var(--black)",
        fifteenOpacityBlack: "var(--fifteen-opacity-black)",
        gradientOpacityBlack: "var(--gradient-opacity-black)",
        warning: "var(--warning)",
        starred: "var(--starred)",
        success: "var(--success)",
        admin: "var(--admin)",
        shop: "var(--shop)",
        user: "var(--user)",
      },
    },
  },
  plugins: [],
};
